# Generated by Django 6.0.4 on 2026-05-01 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEpidemico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.TextField()),
                ('tipo_defecto', models.TextField()),
                ('cantidad', models.IntegerField(default=0)),
                ('estado', models.TextField(default='activo')),
                ('timestamp_inicio', models.DateTimeField(blank=True, null=True)),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True)),
                ('fotos', models.TextField(default='[]')),
                ('user_id', models.IntegerField()),
                ('modelo', models.TextField(blank=True, null=True)),
                ('linea', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lote Epidémico',
                'verbose_name_plural': 'Lotes Epidémicos',
                'db_table': 'lotes_epidemico',
                'ordering': ['-timestamp_inicio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.TextField()),
                ('modelo', models.TextField()),
                ('linea', models.TextField()),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('responsable', models.TextField()),
                ('descripcion', models.TextField()),
                ('modo_epidemico', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Defecto',
                'verbose_name_plural': 'Registros de Defectos',
                'db_table': 'registros_defectos',
                'ordering': ['-fecha_registro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], default='A', max_length=1)),
                ('telegram_user_id', models.IntegerField(blank=True, help_text='ID de Telegram del operador (opcional)', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
