# Generated by Django 6.0.5 on 2026-05-10 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoConversacion',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado_json', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Estado de Conversación',
                'verbose_name_plural': 'Estados de Conversación',
                'db_table': 'estado_conversaciones',
            },
        ),
        migrations.CreateModel(
            name='ContadorGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], max_length=1)),
                ('departamento', models.CharField(choices=[('IQA', 'IQA (Inspección de Calidad)'), ('SQA', 'SQA (Aseguramiento de Calidad)'), ('PROD', 'Producción'), ('ENG', 'Ingeniería')], max_length=10)),
                ('contador_actual', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Contador de Grupo',
                'verbose_name_plural': 'Contadores de Grupo',
                'db_table': 'contadores_grupo',
                'unique_together': {('turno', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], default='A', max_length=1)),
                ('departamento', models.CharField(choices=[('IQA', 'IQA (Inspección de Calidad)'), ('SQA', 'SQA (Aseguramiento de Calidad)'), ('PROD', 'Producción'), ('ENG', 'Ingeniería')], default='IQA', max_length=10)),
                ('rol', models.CharField(default='operador', max_length=20)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, help_text='ID de Telegram del operador', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.TextField()),
                ('modelo', models.TextField()),
                ('linea', models.TextField()),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('responsable', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('turno', models.CharField(blank=True, max_length=1, null=True)),
                ('departamento', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Defecto',
                'verbose_name_plural': 'Registros de Defectos',
                'db_table': 'registros_defectos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['turno', 'departamento'], name='idx_turno_depto'), models.Index(fields=['fecha_registro'], name='idx_fecha')],
            },
        ),
    ]
