# Generated by Django 6.0.4 on 2026-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBot',
            fields=[
                ('telegram_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('turno', models.CharField(max_length=1)),
                ('departamento', models.CharField(max_length=10)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario del Bot',
                'verbose_name_plural': 'Usuarios del Bot',
                'db_table': 'usuarios_bot',
                'ordering': ['-fecha_registro'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LoteEpidemico',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='departamento',
            field=models.CharField(choices=[('IQA', 'IQA (Inspección de Calidad)'), ('SQA', 'SQA (Aseguramiento de Calidad)'), ('PROD', 'Producción'), ('ENG', 'Ingeniería')], default='IQA', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, help_text='ID de Telegram del operador', null=True),
        ),
    ]
