# Generated by Django 6.0.4 on 2026-05-10 01:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodefecto',
            name='comentarios_supervisor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registrodefecto',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('duplicado', 'Duplicado'), ('borroso', 'Borroso')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='registrodefecto',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodefecto',
            name='fotos_nums',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='IDs de foto como enteros. Reemplaza fotos (TextField) gradualmente.'),
        ),
        migrations.AddField(
            model_name='registrodefecto',
            name='is_blurry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrodefecto',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='registrodefecto',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor que revisó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_revisados', to=settings.AUTH_USER_MODEL),
        ),
    ]
