# Generated by Django 6.0.4 on 2026-05-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_usuariobot_delete_loteepidemico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(default='operador', max_length=20),
        ),
    ]
