# Generated by Django 6.0.4 on 2026-06-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0003_phase1_data_migration_fotos_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodefecto',
            name='numero_parte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Parte'),
        ),
    ]
