# Generated by Django 6.0.4 on 2026-06-14 04:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_registrodefecto_numero_parte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('contador_actual', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Contador de Usuario',
                'verbose_name_plural': 'Contadores de Usuario',
                'db_table': 'contadores_usuario',
            },
        ),
        migrations.DeleteModel(
            name='ContadorGrupo',
        ),
        migrations.AlterField(
            model_name='registrodefecto',
            name='fotos_nums',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='IDs de foto como enteros. Reemplaza fotos (TextField) gradualmente.'),
        ),
        migrations.AlterField(
            model_name='registrodefecto',
            name='numero_parte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
