# Generated by Django 6.0.4 on 2026-07-20 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0005_contadorusuario_delete_contadorgrupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaFotografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo', models.CharField(help_text='Ruta relativa o absoluta al archivo', max_length=500)),
                ('orden', models.IntegerField(default=0)),
                ('es_portada', models.BooleanField(default=False)),
                ('angulo_rotacion', models.IntegerField(default=0)),
                ('estado_ia', models.CharField(default='PENDIENTE', max_length=20)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_v2', to='calidad.registrodefecto')),
            ],
            options={
                'verbose_name': 'Evidencia Fotográfica',
                'verbose_name_plural': 'Evidencias Fotográficas',
                'db_table': 'evidencias_fotograficas',
                'ordering': ['registro', 'orden'],
            },
        ),
    ]
