# Generated by Django 6.0.4 on 2026-07-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0007_migrate_fotos_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='fotos', max_length=50, unique=True)),
                ('valor_actual', models.BigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Contador Global',
                'verbose_name_plural': 'Contadores Globales',
                'db_table': 'global_counter',
            },
        ),
        migrations.AlterField(
            model_name='registrodefecto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
