# Generated by Django 6.0.4 on 2026-07-24 12:36

import re
import os
from django.db import migrations

def init_global_counter(apps, schema_editor):
    EvidenciaFotografica = apps.get_model('calidad', 'EvidenciaFotografica')
    GlobalCounter = apps.get_model('calidad', 'GlobalCounter')
    
    max_num = 0
    pattern = re.compile(r'^([0-9]+)_.*$')
    
    for evidencia in EvidenciaFotografica.objects.all():
        if not evidencia.ruta_archivo:
            continue
        filename = os.path.basename(evidencia.ruta_archivo)
        match = pattern.match(filename)
        if match:
            num = int(match.group(1))
            if num > max_num:
                max_num = num
                
    valor_inicial = max_num + 1 if max_num > 0 else 1
    
    GlobalCounter.objects.get_or_create(
        nombre='fotos',
        defaults={'valor_actual': valor_inicial}
    )

def reverse_global_counter(apps, schema_editor):
    GlobalCounter = apps.get_model('calidad', 'GlobalCounter')
    GlobalCounter.objects.filter(nombre='fotos').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0008_globalcounter_alter_registrodefecto_fecha_registro'),
    ]

    operations = [
        migrations.RunPython(init_global_counter, reverse_global_counter),
    ]
