# Generated by Django 6.0.4 on 2026-07-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0009_init_global_counter_from_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroReutilizable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True, unique=True)),
                ('fecha_liberacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número Reutilizable',
                'verbose_name_plural': 'Números Reutilizables',
                'db_table': 'numeros_reutilizables',
                'ordering': ['numero'],
            },
        ),
    ]
