# Generated by Django 6.0.4 on 2026-07-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0010_numeroreutilizable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContadorUsuario',
        ),
    ]
