# Generated by Django 6.0.4 on 2026-07-24 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UPLOADING', 'Subiendo archivos'), ('PROCESSING', 'Procesando en Celery'), ('DRAFT', 'Borrador listo para editar'), ('READY', 'Validado y listo para confirmar'), ('CONFIRMED', 'Confirmado e insertado'), ('EXPIRED', 'Expirado'), ('FAILED', 'Error en el procesamiento')], db_index=True, default='UPLOADING', max_length=20)),
                ('excel_original_name', models.CharField(max_length=255)),
                ('zip_original_name', models.CharField(max_length=255)),
                ('zip_extract_path', models.CharField(max_length=500)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('validated_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='Número de fila en el Excel (1-indexado)')),
                ('raw_data', models.JSONField()),
                ('mapped_data', models.JSONField(blank=True, default=dict)),
                ('assigned_photos', models.JSONField(blank=True, default=list)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='workspace.importsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'is_valid'], name='workspace_d_session_b97bf0_idx')],
                'unique_together': {('session', 'row_index')},
            },
        ),
    ]
